language: node_js
node_js:
    - 0.8
before_install:
    - jdk_switcher use openjdk6
install: ./bootstrap.sh --noprompt --directory ./narwhal
script: jake test
env: PATH=/home/travis/builds/cappuccino/cappuccino/narwhal/bin:$PATH CAPP_BUILD=/home/travis/builds/cappuccino/cappuccino/Build NARWHAL_ENGINE=rhino
